[package]
name = "hot-corners"
version = "0.1.0"
edition = "2021"

[dependencies]
expanduser = "1.2.2"
hyprland = "0.4.0-beta.2"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
